name: dev-login-server CI

on:
    push:
        branches: [ "*" ]
    pull_request:
        branches: [ "*" ]
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix: 
                node-version: [14.x, 16.x, 18.x]
        
        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - run: npm install
    
    test: 
        needs: build
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Test
          uses: actions/setup-node@v4
        - run: npm run test

    docker:
        needs: test
        uses: ./.github/workflows/Docker.yml
        secrets: inherit
